var mongoose = require('mongoose');

var Schema = mongoose.Schema;

var newSchema = new Schema({
  iRefUserId: {type: Number},
  eRefType: {type: String,enum: ['driver', 'rider'],default: 'rider'},
  vFbId: {type: String},
  vName: {type: String},
  vLastName: {type: String},
  vEmail: {type: String},
  vPassword: {type: String},
  vCountry: {type: String},
  vPhone: {type: String},
  eGender: {type: String,default: 'male',enum: ['male', 'female']},
  vCreditCard: {type: String},
  dBirthDate: {type: Date},
  vExpMonth: {type: String},
  vExpYear: {type: String},
  vCvv: {type: String},
  vImgName: {type: String},
  vAvgRating: {type: String,},
  vLogoutDev: {type: Boolean,default: false},
  iGcmRegId: {type: String},
  vCallFromDriver: {type: String},
  iTripId: {type: Number},
  vTripStatus: {type: String},
  vTripPaymentMode: {type: String, enum: ['cash', 'none', 'card'], default: 'cash'},
  iSelectedCarType: {type: Number},
  fPickUpPrice: {type: Number},
  fNightPrice: {type: Number},
  tDestinationLatitude: {type: String},
  tDestinationLongitude: {type: String},
  tDestinationAddress: {type: String},
  vInviteCode: {type: String},
  vCouponCode: {type: String},
  vLang: {type: String},
  eStatus: {type: String, enum:['active', 'inactive', 'deleted'], default: 'active'},
  vPhoneCode: {type: String},
  vZip: {type: String},
  vPassToken: {type: String},
  eDeviceType: {type: String, enum:['ios','android'], default: 'ios'},
  vCurrencyPassenger: {type: String},
  tRegistrationDate: {type: Date},
  iCabBookingId: {type: Number},
  vStripeToken: {type: String},
  vStripeCusId: {type: String},
  eType: {type: String, enum: ['ride', 'driver', 'uber x']},
  iPackageTypeId: {type: Number},
  vReceiverName: {type: String},
  vReceiverMobile: {type: String},
  tPickUpIns: {type: String},
  tDeliveryIns: {type: String},
  tPackageDetails: {type: String},
  eDeliverModule: {type: Boolean},
  iUserPetId: {type: Number},
  iAppVersion: {type: String},
  vRefCode: {type: String},
  dRefDate: {type: Date},
  vLatitude: {type: String},
  vLongitude: {type: String},
  tLastOnline: {type: Date},
  eEmailVerified: {type: Boolean},
  ePhoneVerified: {type: Boolean},
  iQty: {type: Number},
  iUserVehicleId: {type: Number},
  vPasswordToken: {type: String},
  eSignUpType: {type: String, enum:['normal', 'facebook', 'google'], default: 'normal'},
  tSessionId: {type: String},
  vPassword_token: {type: String},
  vRideCountry: {type: String},
  tDeviceSessionId: {type: String}
});

module.exports = mongoose.model('register-user', newSchema);
